In [1]:
import pandas as pd

data = pd.read_csv("../data/accepted_2007_to_2018Q4.csv", nrows = 5)
pd.set_option('display.max_columns', None)
data.head()

,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,emp_title,emp_length,home_ownership,annual_inc,verification_status,issue_d,loan_status,pymnt_plan,url,desc,purpose,title,zip_code,addr_state,dti,delinq_2yrs,earliest_cr_line,fico_range_low,fico_range_high,inq_last_6mths,mths_since_last_delinq,mths_since_last_record,open_acc,pub_rec,revol_bal,revol_util,total_acc,initial_list_status,out_prncp,out_prncp_inv,total_pymnt,total_pymnt_inv,total_rec_prncp,total_rec_int,total_rec_late_fee,recoveries,collection_recovery_fee,last_pymnt_d,last_pymnt_amnt,next_pymnt_d,last_credit_pull_d,last_fico_range_high,last_fico_range_low,collections_12_mths_ex_med,mths_since_last_major_derog,policy_code,application_type,annual_inc_joint,dti_joint,verification_status_joint,acc_now_delinq,tot_coll_amt,tot_cur_bal,open_acc_6m,open_act_il,open_il_12m,open_il_24m,mths_since_rcnt_il,total_bal_il,il_util,open_rv_12m,open_rv_24m,max_bal_bc,all_util,total_rev_hi_lim,inq_fi,total_cu_tl,inq_last_12m,acc_open_past_24mths,avg_cur_bal,bc_open_to_buy,bc_util,chargeoff_within_12_mths,delinq_amnt,mo_sin_old_il_acct,mo_sin_old_rev_tl_op,mo_sin_rcnt_rev_tl_op,mo_sin_rcnt_tl,mort_acc,mths_since_recent_bc,mths_since_recent_bc_dlq,mths_since_recent_inq,mths_since_recent_revol_delinq,num_accts_ever_120_pd,num_actv_bc_tl,num_actv_rev_tl,num_bc_sats,num_bc_tl,num_il_tl,num_op_rev_tl,num_rev_accts,num_rev_tl_bal_gt_0,num_sats,num_tl_120dpd_2m,num_tl_30dpd,num_tl_90g_dpd_24m,num_tl_op_past_12m,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,revol_bal_joint,sec_app_fico_range_low,sec_app_fico_range_high,sec_app_earliest_cr_line,sec_app_inq_last_6mths,sec_app_mort_acc,sec_app_open_acc,sec_app_revol_util,sec_app_open_act_il,sec_app_num_rev_accts,sec_app_chargeoff_within_12_mths,sec_app_collections_12_mths_ex_med,sec_app_mths_since_last_major_derog,hardship_flag,hardship_type,hardship_reason,hardship_status,deferral_term,hardship_amount,hardship_start_date,hardship_end_date,payment_plan_start_date,hardship_length,hardship_dpd,hardship_loan_status,orig_projected_additional_accrued_interest,hardship_payoff_balance_amount,hardship_last_payment_amount,disbursement_method,debt_settlement_flag,debt_settlement_flag_date,settlement_status,settlement_date,settlement_amount,settlement_percentage,settlement_term
0,68407277,NaN,3600.0,3600.0,3600.0,36 months,13.99,123.03,C,C4,leadman,10+ years,MORTGAGE,55000.0,Not Verified,Dec-2015,Fully Paid,n,https://lendingclub.com/browse/loanDetail.acti...,NaN,debt_consolidation,Debt consolidation,190xx,PA,5.91,0.0,Aug-2003,675.0,679.0,1.0,30.0,NaN,7.0,0.0,2765.0,29.7,13.0,w,0.00,0.00,4421.723917,4421.72,3600.00,821.72,0.0,0.0,0.0,Jan-2019,122.67,NaN,Mar-2019,564.0,560.0,0.0,30.0,1.0,Individual,NaN,NaN,NaN,0.0,722.0,144904.0,2.0,2.0,0.0,1.0,21.0,4981.0,36.0,3.0,3.0,722.0,34.0,9300.0,3.0,1.0,4.0,4.0,20701.0,1506.0,37.2,0.0,0.0,148.0,128.0,3.0,3.0,1.0,4.0,69.0,4.0,69.0,2.0,2.0,4.0,2.0,5.0,3.0,4.0,9.0,4.0,7.0,0.0,0.0,0.0,3.0,76.9,0.0,0.0,0.0,178050.0,7746.0,2400.0,13734.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
1,68355089,NaN,24700.0,24700.0,24700.0,36 months,11.99,820.28,C,C1,Engineer,10+ years,MORTGAGE,65000.0,Not Verified,Dec-2015,Fully Paid,n,https://lendingclub.com/browse/loanDetail.acti...,NaN,small_business,Business,577xx,SD,16.06,1.0,Dec-1999,715.0,719.0,4.0,6.0,NaN,22.0,0.0,21470.0,19.2,38.0,w,0.00,0.00,25679.660000,25679.66,24700.00,979.66,0.0,0.0,0.0,Jun-2016,926.35,NaN,Mar-2019,699.0,695.0,0.0,NaN,1.0,Individual,NaN,NaN,NaN,0.0,0.0,204396.0,1.0,1.0,0.0,1.0,19.0,18005.0,73.0,2.0,3.0,6472.0,29.0,111800.0,0.0,0.0,6.0,4.0,9733.0,57830.0,27.1,0.0,0.0,113.0,192.0,2.0,2.0,4.0,2.0,NaN,0.0,6.0,0.0,5.0,5.0,13.0,17.0,6.0,20.0,27.0,5.0,22.0,0.0,0.0,0.0,2.0,97.4,7.7,0.0,0.0,314017.0,39475.0,79300.0,24667.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
2,68341763,NaN,20000.0,20000.0,20000.0,60 months,10.78,432.66,B,B4,truck driver,10+ years,MORTGAGE,63000.0,Not Verified,Dec-2015,Fully Paid,n,https://lendingclub.com/browse/loanDetail.acti...,NaN,home_improvement,NaN,605xx,IL,10.78,0.0,Aug-2000,695.0,699.0,0.0,NaN,NaN,6.0,0.0,7869.0,56.2,18.0,w,0.00,0.00,22705.924294,22705.92,20000.00,2705.92,0.0,0.0,0.0,Jun-2017,15813.30,NaN,Mar-2019,704.0,700.0,0.0,NaN,1.0,Joint App,71000.0,13.85,Not Verified,0.0,0.0,189699.0,0.0,1.0,0.0,4.0,19.0,10827.0,73.0,0.0,2.0,2081.0,65.0,14000.0,2.0,5.0,1.0,6.0,31617.0,2737.0,55.9,0.0,0.0,125.0,184.0,14.0,14.0,5.0,101.0,NaN,10.0,NaN,0.0,2.0,3.0,2.0,4.0,6.0,4.0,7.0,3.0,6.0,0.0,0.0,0.0,0.0,100.0,50.0,0.0,0.0,218418.0,18696.0,6200.0,14877.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
3,66310712,NaN,35000.0,35000.0,35000.0,60 months,14.85,829.90,C,C5,Information Systems Officer,10+ years,MORTGAGE,110000.0,Source Verified,Dec-2015,Current,n,https://lendingclub.com/browse/loanDetail.acti...,NaN,debt_consolidation,Debt consolidation,076xx,NJ,17.06,0.0,Sep-2008,785.0,789.0,0.0,NaN,NaN,13.0,0.0,7802.0,11.6,17.0,w,15897.65,15897.65,31464.010000,31464.01,19102.35,12361.66,0.0,0.0,0.0,Feb-2019,829.90,Apr-2019,Mar-2019,679.0,675.0,0.0,NaN,1.0,Individual,NaN,NaN,NaN,0.0,0.0,301500.0,1.0,1.0,0.0,1.0,23.0,12609.0,70.0,1.0,1.0,6987.0,45.0,67300.0,0.0,1.0,0.0,2.0,23192.0,54962.0,12.1,0.0,0.0,36.0,87.0,2.0,2.0,1.0,2.0,NaN,NaN,NaN,0.0,4.0,5.0,8.0,10.0,2.0,10.0,13.0,5.0,13.0,0.0,0.0,0.0,1.0,100.0,0.0,0.0,0.0,381215.0,52226.0,62500.0,18000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
4,68476807,NaN,10400.0,10400.0,10400.0,60 months,22.45,289.91,F,F1,Contract Specialist,3 years,MORTGAGE,104433.0,Source Verified,Dec-2015,Fully Paid,n,https://lendingclub.com/browse/loanDetail.acti...,NaN,major_purchase,Major purchase,174xx,PA,25.37,1.0,Jun-1998,695.0,699.0,3.0,12.0,NaN,12.0,0.0,21929.0,64.5,35.0,w,0.00,0.00,11740.500000,11740.50,10400.00,1340.50,0.0,0.0,0.0,Jul-2016,10128.96,NaN,Mar-2018,704.0,700.0,0.0,NaN,1.0,Individual,NaN,NaN,NaN,0.0,0.0,331730.0,1.0,3.0,0.0,3.0,14.0,73839.0,84.0,4.0,7.0,9702.0,78.0,34000.0,2.0,1.0,3.0,10.0,27644.0,4567.0,77.5,0.0,0.0,128.0,210.0,4.0,4.0,6.0,4.0,12.0,1.0,12.0,0.0,4.0,6.0,5.0,9.0,10.0,7.0,19.0,6.0,12.0,0.0,0.0,0.0,4.0,96.6,60.0,0.0,0.0,439570.0,95768.0,20300.0,88097.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN

In [2]:
data = pd.read_csv('../data/accepted_2007_to_2018Q4.csv', nrows=100000)
data['loan_status'].value_counts()

C:\Users\zheny\AppData\Local\Temp\ipykernel_16572\4228517577.py:1: DtypeWarning: Columns (0: desc) have mixed types. Specify dtype option on import or set low_memory=False.
  data = pd.read_csv('../data/accepted_2007_to_2018Q4.csv', nrows=100000)

loan_status
Fully Paid            70288
Charged Off           17603
Current               11402
Late (31-120 days)      441
In Grace Period         199
Late (16-30 days)        66
Default                   1
Name: count, dtype: int64

In [3]:
data = data[data['loan_status'].isin(['Fully Paid','Charged Off','Default'])]
data['loan_status'].value_counts()

loan_status
Fully Paid     70288
Charged Off    17603
Default            1
Name: count, dtype: int64

In [4]:
data['default'] = data['loan_status'].apply(lambda x: 0 if x == 'Fully Paid' else 1 )

C:\Users\zheny\AppData\Local\Temp\ipykernel_16572\4023593816.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  data['default'] = data['loan_status'].apply(lambda x: 0 if x == 'Fully Paid' else 1 )

In [5]:
data['default'].value_counts()

default
0    70288
1    17604
Name: count, dtype: int64

In [6]:
data['default'].value_counts(normalize=bool)

default
0    0.799709
1    0.200291
Name: proportion, dtype: float64

In [7]:
pd.set_option('display.max_rows',None)
filter = (data.isna().sum().sort_values(ascending=False)/data.shape[0])*100
filter = filter[filter < 40].index
data = data[filter]
data.shape

(87892, 94)

In [8]:
data.columns.tolist()
descriptions = pd.read_excel('../data/LCDataDictionary.xlsx')
descriptions = descriptions[descriptions['LoanStatNew'].isin(data.columns)]
descriptions.head()

            LoanStatNew                                        Description
0        acc_now_delinq  The number of accounts on which the borrower i...
1  acc_open_past_24mths         Number of trades opened in past 24 months.
2            addr_state  The state provided by the borrower in the loan...
4            annual_inc  The self-reported annual income provided by th...
6      application_type  Indicates whether the loan is an individual ap...

In [9]:
leakage_cols = ['total_pymnt', 'total_pymnt_inv', 'total_rec_prncp', 'total_rec_int', 
                'total_rec_late_fee', 'recoveries', 'collection_recovery_fee', 
                'last_pymnt_d', 'last_pymnt_amnt', 'out_prncp', 'out_prncp_inv', 
                'last_credit_pull_d', 'last_fico_range_high', 'last_fico_range_low', 
                'hardship_flag', 'debt_settlement_flag', 'disbursement_method']
data = data.drop(columns=leakage_cols)

In [10]:
data.columns.tolist()
data.dtypes

mths_since_recent_inq         float64
emp_title                         str
emp_length                        str
num_tl_120dpd_2m              float64
mo_sin_old_il_acct            float64
percent_bc_gt_75              float64
bc_util                       float64
bc_open_to_buy                float64
mths_since_recent_bc          float64
title                             str
revol_util                    float64
dti                           float64
num_rev_accts                 float64
funded_amnt                   float64
id                              int64
loan_amnt                     float64
loan_status                       str
pymnt_plan                        str
verification_status               str
issue_d                           str
grade                             str
sub_grade                         str
annual_inc                    float64
home_ownership                    str
funded_amnt_inv               float64
term                              str
int_rate                      float64
installment                   float64
addr_state                        str
zip_code                          str
purpose                           str
url                               str
mo_sin_rcnt_tl                float64
mo_sin_rcnt_rev_tl_op         float64
mo_sin_old_rev_tl_op          float64
delinq_amnt                   float64
tot_cur_bal                   float64
tot_coll_amt                  float64
acc_now_delinq                float64
application_type                  str
fico_range_low                float64
earliest_cr_line                  str
inq_last_6mths                float64
delinq_2yrs                   float64
initial_list_status               str
total_acc                     float64
collections_12_mths_ex_med    float64
policy_code                   float64
revol_bal                     float64
pub_rec                       float64
open_acc                      float64
fico_range_high               float64
chargeoff_within_12_mths      float64
total_rev_hi_lim              float64
acc_open_past_24mths          float64
avg_cur_bal                   float64
total_bc_limit                float64
total_bal_ex_mort             float64
total_il_high_credit_limit    float64
num_tl_90g_dpd_24m            float64
num_op_rev_tl                 float64
num_il_tl                     float64
num_rev_tl_bal_gt_0           float64
num_sats                      float64
num_accts_ever_120_pd         float64
mort_acc                      float64
num_actv_bc_tl                float64
num_actv_rev_tl               float64
pct_tl_nvr_dlq                float64
pub_rec_bankruptcies          float64
tax_liens                     float64
tot_hi_cred_lim               float64
num_tl_30dpd                  float64
num_tl_op_past_12m            float64
num_bc_sats                   float64
num_bc_tl                     float64
default                         int64
dtype: object

In [11]:
data['emp_length'].unique()

<StringArray>
['10+ years',   '3 years',   '4 years',   '6 years',   '7 years',   '8 years',
   '2 years',   '5 years',   '9 years',  '< 1 year',    '1 year',         nan]
Length: 12, dtype: str

In [12]:
data['term'].unique()

<StringArray>
[' 36 months', ' 60 months']
Length: 2, dtype: str

In [13]:
years = {'10+ years': 10,   '3 years': 3,   '4 years': 4,   '6 years': 6,   '7 years': 7,   '8 years': 8, '2 years': 2,   '5 years': 5,   '9 years': 9,  '< 1 year': 0,    '1 year': 1} 
data['emp_length'] = data['emp_length'].map(years)
data['emp_length'].unique()

array([10.,  3.,  4.,  6.,  7.,  8.,  2.,  5.,  9.,  0.,  1., nan])

In [14]:
months = {' 36 months': 36, ' 60 months': 60}
data['term'] = data['term'].map(months)
data['term'].unique()

array([36, 60])

In [15]:
data['issue_d'].head()

0    Dec-2015
1    Dec-2015
2    Dec-2015
4    Dec-2015
5    Dec-2015
Name: issue_d, dtype: str

In [16]:
data['earliest_cr_line'].head()

0    Aug-2003
1    Dec-1999
2    Aug-2000
4    Jun-1998
5    Oct-1987
Name: earliest_cr_line, dtype: str

In [17]:
data['issue_d'] = pd.to_datetime(data['issue_d'],format='%b-%Y')
data['issue_d'].head()

0   2015-12-01
1   2015-12-01
2   2015-12-01
4   2015-12-01
5   2015-12-01
Name: issue_d, dtype: datetime64[us]

In [18]:
data['earliest_cr_line'] = pd.to_datetime(data['earliest_cr_line'], format = '%b-%Y')
data['earliest_cr_line'].head()

0   2003-08-01
1   1999-12-01
2   2000-08-01
4   1998-06-01
5   1987-10-01
Name: earliest_cr_line, dtype: datetime64[us]

In [19]:
credit_history_length = data['issue_d'] - data['earliest_cr_line']
credit_history_length.head()

0    4505 days
1    5844 days
2    5600 days
4    6392 days
5   10288 days
dtype: timedelta64[us]

In [20]:
credit_history_length = credit_history_length.dt.days/365
credit_history_length.head()

0    12.342466
1    16.010959
2    15.342466
4    17.512329
5    28.186301
dtype: float64

In [21]:
credit_history_length.describe()

count    87892.000000
mean        16.742321
std          7.679278
min          3.082192
25%         11.424658
50%         15.175342
75%         20.682192
max         65.958904
dtype: float64

In [22]:
data['credit_history_years'] = credit_history_length

In [23]:
print(data['policy_code'].unique())
print(data['emp_title'].nunique())
print(data['title'].nunique())
print(data['zip_code'].nunique())

[1.]
33660
13
878

In [24]:
data['title'].unique()

<StringArray>
[     'Debt consolidation',                'Business',
                       nan,          'Major purchase',
 'Credit card refinancing',        'Home improvement',
                   'Other',             'Home buying',
                'Vacation',           'Car financing',
        'Medical expenses',   'Moving and relocation',
              'Green loan',                 'odymeds']
Length: 14, dtype: str

In [25]:
data['purpose'].unique()

<StringArray>
['debt_consolidation',     'small_business',   'home_improvement',
     'major_purchase',        'credit_card',              'other',
              'house',           'vacation',                'car',
            'medical',             'moving',   'renewable_energy']
Length: 12, dtype: str

In [26]:
obsolete = ['policy_code', 'emp_title', 'zip_code', 'title', 'url', 'id', 'loan_status', 'issue_d', 'earliest_cr_line']
data = data.drop(columns=obsolete)

In [27]:
print(data.shape)
print(data.dtypes)

(87892, 69)
mths_since_recent_inq         float64
emp_length                    float64
num_tl_120dpd_2m              float64
mo_sin_old_il_acct            float64
percent_bc_gt_75              float64
bc_util                       float64
bc_open_to_buy                float64
mths_since_recent_bc          float64
revol_util                    float64
dti                           float64
num_rev_accts                 float64
funded_amnt                   float64
loan_amnt                     float64
pymnt_plan                        str
verification_status               str
grade                             str
sub_grade                         str
annual_inc                    float64
home_ownership                    str
funded_amnt_inv               float64
term                            int64
int_rate                      float64
installment                   float64
addr_state                        str
purpose                           str
mo_sin_rcnt_tl                float64
mo_sin_rcnt_rev_tl_op         float64
mo_sin_old_rev_tl_op          float64
delinq_amnt                   float64
tot_cur_bal                   float64
tot_coll_amt                  float64
acc_now_delinq                float64
application_type                  str
fico_range_low                float64
inq_last_6mths                float64
delinq_2yrs                   float64
initial_list_status               str
total_acc                     float64
collections_12_mths_ex_med    float64
revol_bal                     float64
pub_rec                       float64
open_acc                      float64
fico_range_high               float64
chargeoff_within_12_mths      float64
total_rev_hi_lim              float64
acc_open_past_24mths          float64
avg_cur_bal                   float64
total_bc_limit                float64
total_bal_ex_mort             float64
total_il_high_credit_limit    float64
num_tl_90g_dpd_24m            float64
num_op_rev_tl                 float64
num_il_tl                     float64
num_rev_tl_bal_gt_0           float64
num_sats                      float64
num_accts_ever_120_pd         float64
mort_acc                      float64
num_actv_bc_tl                float64
num_actv_rev_tl               float64
pct_tl_nvr_dlq                float64
pub_rec_bankruptcies          float64
tax_liens                     float64
tot_hi_cred_lim               float64
num_tl_30dpd                  float64
num_tl_op_past_12m            float64
num_bc_sats                   float64
num_bc_tl                     float64
default                         int64
credit_history_years          float64
dtype: object

In [28]:
data['issue'].head()

KeyError: 'issue'

In [ ]:
data = data.drop(columns='issue')

In [ ]:
data['grade'].unique()

In [ ]:
grades = {'C':3, 'B':2, 'F':6, 'A':1, 'E':5, 'D':4, 'G':7}
data['grade'] = data['grade'].map(grades)
data['grade'].head()

In [ ]:
data['grade'].unique()

In [ ]:
data = data.drop(columns='sub_grade')

In [ ]:
data = pd.get_dummies(data = data,columns=['home_ownership', 'purpose', 'addr_state', 'verification_status', 'application_type', 'initial_list_status', 'pymnt_plan'],drop_first=True)

In [ ]:
data.shape

In [ ]:
data.dtypes.value_counts()

In [ ]:
data.isna().sum().sort_values(ascending=False)

In [ ]:
data['dti'] = data['dti'].fillna(data['dti'].median())
data['dti'].isna().sum()

In [ ]:
data['revol_util'] = data['revol_util'].fillna(data['revol_util'].median())

In [ ]:
data['num_rev_accts'] = data['num_rev_accts'].fillna(data['num_rev_accts'].median())

In [ ]:
data[['dti','revol_util','num_rev_accts']].isna().sum()

In [ ]:
descriptions[descriptions['LoanStatNew'].isin(['mths_since_recent_inq', 'num_tl_120dpd_2m', 'mo_sin_old_il_acct', 'percent_bc_gt_75', 'bc_util', 'bc_open_to_buy', 'mths_since_recent_bc'])]

In [ ]:
data['mo_sin_old_il_acct_was_missing'] = data['mo_sin_old_il_acct'].isna().astype(int)
data['mo_sin_old_il_acct'] = data['mo_sin_old_il_acct'].fillna(data['mo_sin_old_il_acct'].max())

In [ ]:
fill_with_max = ['mths_since_recent_bc', 'mths_since_recent_inq']
fill_with_zero = ['bc_open_to_buy', 'bc_util', 'percent_bc_gt_75', 'num_tl_120dpd_2m']
for i in fill_with_max:
    data[i + "_was missing"] = data[i].isna().astype(int)
    data[i] = data[i].fillna(data[i].max())
for j in fill_with_zero:
    data[j+ "_was missing"] = data[j].isna().astype(int)
    data[j] = data[j].fillna(0)

In [ ]:
data.isna().sum()

In [ ]:
data['emp_length_was_missing'] = data['emp_length'].isna().astype(int)
data['emp_length'] = data['emp_length'].fillna(0)

In [29]:
from sklearn.model_selection import train_test_split
y = data['default']
X = data.drop(columns='default')
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=123,stratify=y)

In [30]:
y_train.value_counts(normalize=True)
y_test.value_counts(normalize=True)

default
0    0.799704
1    0.200296
Name: proportion, dtype: float64